### PR TITLE
ref #435: remove handling of cms_workflow_actiontype_id field from ol…

### PR DESCRIPTION
**Pull request by pixeljunkie**
…d workflow bundle

| Q             | A
| ------------- | ---
| Branch        | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed issues  | chameleon-system/chameleon-system#435
| License       | MIT

### CODE REVIEW

**Comment by pixeljunkie** [comment]
A cosmetic code change, found during working on another issue (the field does not exist, so it will do no harm to remove it). I think it is okay, to let this 7.0.x only.

**Comment by UlrichKu** [comment]
This should be merged to 7.0.x?

**Comment by pixeljunkie** [comment]
Whoops. You are right. Will add a new PR.

**Comment by UlrichKu** [comment]
> Whoops. You are right. Will add a new PR.

You can simply change the target.

**Pull request closed without merging**
