### PR TITLE
Feature/245 replace color picker

### PR DESCRIPTION
**Pull request by pixeljunkie**
| Q             | A
| ------------- | ---
| Branch        | master 
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed issues  | chameleon-system/chameleon-system#245
| License       | MIT

### CODE REVIEW

**Comment by pixeljunkie** [comment]
Please note: This PR is based on: https://github.com/chameleon-system/chameleon-base/pull/135 and needs a merge of this first.

**Comment by umulmrum** [comment]
There are conflicts in the branch (and the theme PR is merged, maybe it's best to rebase this branch onto current master).

**Comment by pixeljunkie** [comment]
The PR is now rebased to master.

**Comment by umulmrum** [comment]
Thanks @pixeljunkie

**Pull request merged**
