### PR TITLE
ref #373: delete CMSFieldMLT - not used anywhere

### PR DESCRIPTION
**Pull request by pixeljunkie**
| Q             | A
| ------------- | ---
| Branch        | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
| Fixed issues  | chameleon-system/chameleon-system#373
| License       | MIT

### CODE REVIEW

**Comment by pixeljunkie** [comment]
The class is not used since 2009 says the internal GIT and it was marked for removal with a deleteme txt file. I know this is not the right practice, but this were other times. And the file is useless because the database structure changed. Would it be o.k. for you if we mark it deprecated in 6.3.1. I would not want to wait another year to get rid of this orphan.

**Comment by umulmrum** [comment]
OK let's do this. But there is a merge conflict - could you have a look?

**Comment by pixeljunkie** [comment]
merge conflict fixed.

**Comment by umulmrum** [comment]
Thanks @pixeljunkie

**Pull request merged**
