### PR TITLE
ref #192: remove orphaned files from experimental module MTVersionInfo

### PR DESCRIPTION
**Pull request by pixeljunkie**
… which was never part of the core and is not usable anyway

| Q             | A
| ------------- | ---
| Branch        | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed issues  | chameleon-system/chameleon-system#192
| License       | MIT

### CODE REVIEW

**Comment by umulmrum** [comment]
See https://github.com/chameleon-system/chameleon-system/issues/193#issuecomment-438638297 - could you file a deprecation PR @pixeljunkie?

**Comment by umulmrum** [comment]
Do not merge yet - see chameleon-system/chameleon-system#193 (comment)

**Comment by pixeljunkie** [comment]
deprecated the orphaned files

**Comment by umulmrum** [comment]
Thanks @pixeljunkie

**Pull request merged**
